name: 'build-test'

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          yarn install && yarn build:packaged
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          latest: '@axe-core/playwright,@axe-core/webdriverjs'
          next: 'rem-this,coffee-crypto-cli'
